### ISSUE TITLE
Բացակայող հայերեն կատակ README.md-ում

### ISSUE THREAD

**Issue by Roolman** [justMadridist/selaut#1]
Հայն ամուսնացել է ադրբեջանցու հետ. Բաքվի հայտնի ջարդերից հետո ընտանիքը ստիպված է եղել ապաստան խնդրել այլ երկրում։ Որոշ ժամանակ անց նրանց այցելում է կնոջ եղբայրը։ Նստեցին, խմեցին ու ինչպես միշտ սկսեցին վիճել Ղարաբաղի մասին՝ «ով է ճիշտ, ով է սխալ»։ Նրանք հուզվեցին, իսկ հետո հայը, իրավիճակը լիցքաթափելու համար, ասաց՝ գնանք հարազատներիս մոտ, նրանք մոտակայքում են ապրում՝ նույն գյուղում։ Գնա։ Արածող ոչխարներով դաշտերով անցնում են, հետո ադրբեջանցին ասում է. «Լսե՛ք, մենք, իմ կարծիքով, արդեն հասել ենք, այստեղ ձեր ոչխար բարեկամներն են արածում»։ Ինչին հայը պատասխանում է. «Այո, հարազատներս, միայն կնոջ կողմից»:

**Comment by justMadridist** [comment]
that's very interesting commit and push it for new repository

**Comment by Roolman** [comment]
thank you
